# Generated by Django 5.0 on 2023-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('verified', models.BooleanField(default=False)),
                ('worker_image', models.ImageField(default='', upload_to='static/media/worker_image/')),
                ('citizenship_image_front', models.ImageField(default='', upload_to='static/media/citizenship_image_front/')),
                ('citizenship_image_back', models.ImageField(default='', upload_to='static/media/citizenship_image_back/')),
            ],
        ),
    ]
