# Generated by Django 5.0 on 2023-12-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0003_workerstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30, unique=True)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='worker_image',
        ),
        migrations.AddField(
            model_name='workerstat',
            name='workarea',
            field=models.CharField(choices=[('EL', 'Electrical Services'), ('CA', 'Carpentry'), ('AR', 'Appliance Repair'), ('PA', 'Painting'), ('GA', 'Gardening/Landscaping'), ('RO', 'Roofing'), ('HV', 'HVAC (Heating, Ventilation, and Air Conditioning)'), ('FI', 'Flooring Installation/Repair'), ('WI', 'Window Installation/Repair'), ('LO', 'Locksmith Services'), ('PC', 'Pest Control'), ('DI', 'Drywall Installation/Repair'), ('FA', 'Furniture Assembly'), ('PW', 'Pressure Washing'), ('TI', 'Tile Installation/Repair'), ('HS', 'Home Security Installation'), ('ST', 'Septic Tank Maintenance'), ('GD', 'Garage Door Installation/Repair'), ('CS', 'Chimney Sweeping/Repair'), ('CI', 'Cabinet Installation/Repair'), ('FI', 'Fence Installation/Repair'), ('DC', 'Deck Construction/Repair'), ('GU', 'Gutter Cleaning/Installation'), ('CW', 'Concrete Work'), ('HT', 'Home Theater Installation'), ('PL', 'Plastering'), ('WP', 'Waterproofing'), ('SI', 'Solar Panel Installation'), ('ID', 'Interior Design'), ('HI', 'Home Inspection Services')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rojgar.userdata'),
            preserve_default=False,
        ),
    ]
