# Generated by Django 5.0 on 2023-12-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0005_alter_workerstat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AddField(
            model_name='workerstat',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='grand_father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='permanent_address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='province',
            field=models.CharField(choices=[('KP', 'Koshi Pradesh'), ('MP', 'Madhesh Pradesh'), ('BP', 'Bagmati Pradesh'), ('GP', 'Gandaki Pradesh'), ('LP', 'Lumbini Pradesh'), ('KA', 'Karnali Pradesh'), ('SP', 'Sudurpaschim Pradesh')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='temporary_address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False),
        ),
    ]
