# Generated by Django 5.0 on 2023-12-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0006_remove_userdata_id_workerstat_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstat',
            name='user',
        ),
        migrations.AddField(
            model_name='workerstat',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rojgar.userdata'),
            preserve_default=False,
        ),
    ]
