# Generated by Django 5.0 on 2023-12-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0007_remove_workerstat_user_workerstat_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstat',
            name='province',
        ),
    ]
