# Generated by Django 5.0 on 2023-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0008_remove_workerstat_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstat',
            name='workarea',
            field=models.CharField(choices=[('EL', 'Electrical Services'), ('CA', 'Carpentry'), ('AR', 'Appliance Repair'), ('PA', 'Painting'), ('GA', 'Gardening/Landscaping'), ('RO', 'Roofing'), ('HV', 'HVAC (Heating, Ventilation, and Air Conditioning)'), ('FI', 'Flooring Installation/Repair'), ('WI', 'Window Installation/Repair'), ('LO', 'Locksmith Services'), ('PC', 'Pest Control'), ('DI', 'Drywall Installation/Repair'), ('FA', 'Furniture Assembly'), ('PW', 'Pressure Washing'), ('TI', 'Tile Installation/Repair'), ('HS', 'Home Security Installation'), ('ST', 'Septic Tank Maintenance'), ('GD', 'Garage Door Installation/Repair'), ('CS', 'Chimney Sweeping/Repair'), ('CI', 'Cabinet Installation/Repair'), ('FI', 'Fence Installation/Repair'), ('DC', 'Deck Construction/Repair'), ('GU', 'Gutter Cleaning/Installation'), ('CW', 'Concrete Work'), ('HT', 'Home Theater Installation'), ('PL', 'Plastering'), ('WP', 'Waterproofing'), ('SI', 'Solar Panel Installation'), ('ID', 'Interior Design'), ('HI', 'Home Inspection Services'), ('OT', 'Others')], default='', max_length=30),
        ),
    ]
