# Generated by Django 5.0 on 2023-12-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0010_alter_user_request_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstat',
            name='user_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
