# Generated by Django 5.0 on 2023-12-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0013_alter_workerstat_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstat',
            name='user_name',
        ),
    ]
