# Generated by Django 5.0 on 2023-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0015_alter_workerstat_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workerstat',
            name='worker_district',
            field=models.CharField(default='', max_length=50),
        ),
    ]
