# Generated by Django 5.0 on 2023-12-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0016_user_request_district_workerstat_worker_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='work_done',
            field=models.BooleanField(default=False),
        ),
    ]
