# Generated by Django 5.0 on 2023-12-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0017_user_request_work_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_request',
            name='work_done',
        ),
    ]
