# Generated by Django 5.0 on 2023-12-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0020_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstat',
            name='citizenship_image_back',
            field=models.ImageField(default='', upload_to='media//'),
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='citizenship_image_front',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
