# Generated by Django 5.0 on 2023-12-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0020_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='phone',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
