# Generated by Django 5.0 on 2023-12-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0021_alter_workerstat_citizenship_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstat',
            name='citizenship_image_back',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
