# Generated by Django 5.0 on 2023-12-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgar', '0021_alter_user_request_phone'),
        ('Rojgar', '0022_alter_workerstat_citizenship_image_back'),
    ]

    operations = [
    ]
